/*
 * This source file was generated by the Gradle 'init' task
 */
package estructurasparcial4;

import estructurasparcial4.Service.LeerPerfiles;
import estructurasparcial4.Model.Perfil;
import java.util.List;

public class App {

    public static void main(String[] args) {
        LeerPerfiles lector = new LeerPerfiles();

        lector.leerArchivo();
        List<Perfil> perfiles = lector.obtenerPerfilesLeidos();

        System.out.println("Perfiles cargados:");
        for (Perfil perfil : perfiles) {
            System.out.println(perfil);
        }
    }
}
